baseurl = "https://ollivier.com.br"
title = "Marco Paulo Ollivier"
theme = "hugo-coder"
languagecode = "pt-br"
defaultcontentlanguage = "pt-br"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Marco Paulo Ollivier"
    info = "Software Engineer @ OLX"
    description = "Marco Paulo Ollivier's personal website"
    keywords = "blog,developer,personal"
    #avatarurl = "images/avatar.jpg"
    avatarurl = "https://avatars1.githubusercontent.com/u/697445?s=460&v=4"
    
    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "--- xXx ---"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/marcopollivier/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com/marcopollivier/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/marcopollivier/"
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin fa-2x"
    weight = 4
    url = "https://www.linkedin.com/in/marcopollivier"
[[params.social]]
    name = "Responsive BR"
    icon = "fab fa-medium"
    weight = 5
    url  = "https://medium.com/responsive-br"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url = "https://medium.com/@marcopollivier"
[[menu.main]]
    name = "Presentation"
    weight = 2
    url = "https://speakerdeck.com/marcopollivier"
[[menu.main]]
    name = "Meetup"
    weight = 3
    url = "#"
[[menu.main]]
    name = "My Meetup"
    weight = 4
    url = "https://www.meetup.com/members/233822612"
[[menu.main]]
    name = "Stack Over Flow"
    weight = 5
    url = "https://stackoverflow.com/users/1913089/marco-paulo-ollivier"